version: 0.1

workflows:
  main:
    jobs:
    - build

jobs:
  build:
    steps:
    - clone

    - cache_restore:
        path: .buildx-cache
        key: 'buildx-{{ hash "composer.lock" }}-v1'

    - run: wget -qO- https://api.wodby.com/v1/get/cli | sh
    - run: wodby ci init $WODBY_BUILD_ID

    - run: wodby ci build --cache-dir .buildx-cache

    - cache_save:
        key: 'buildx-{{ hash "composer.lock" }}-v1'
        path: .buildx-cache

    - run: wodby ci release
    - run: wodby ci deploy
