version: 0.1

workflows:
  main:
    jobs:
    - build

jobs:
  build:
    steps:
    - clone

    - cache_restore:
        path: ~/.composer
        key: 'composer-{{ hash "composer.lock" }}-v1'

    - run: wget -qO- https://api.wodby.com/v1/get/cli | sh
    - run: wodby ci init $WODBY_BUILD_ID

    # use wodby ci run instead of wodby ci build with buildx cache because we need to scaffold web/ for nginx image.
    - run: wodby ci run -v $HOME/.composer:/home/wodby/.composer -- composer install -n --no-ansi
    - run: wodby ci build

    - cache_save:
        key: 'composer-{{ hash "composer.lock" }}-v1'
        path: ~/.composer

    - run: wodby ci release
    - run: wodby ci deploy
